resolver: lts-22.44

# due to functor-infix
allow-newer: true

packages:
  - 'grin'

extra-deps:
  - git: https://github.com/csabahruska/functor-infix.git
    commit: 5f91376b93a4f82624ae9416de3fd7597d428564
  - QuickCheck-GenT-0.2.0
  - set-extra-1.4.2
  - system-posix-redirect-1.1.0.1
  - git: https://github.com/llvm-hs/llvm-hs.git
    commit: 5bca2c1a2a3aa98ecfb19181e7a5ebbf3e212b76  # llvm-15 branch
    subdirs:
      - llvm-hs
      - llvm-hs-pure

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
